// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsm0pDusJ7KA8cIkF6BO0-UNhJv3OCWuU',
    appId: '1:576136181155:web:dcadb9f5928857718d1616',
    messagingSenderId: '576136181155',
    projectId: 'ecommerce-app-64233',
    authDomain: 'ecommerce-app-64233.firebaseapp.com',
    storageBucket: 'ecommerce-app-64233.appspot.com',
    measurementId: 'G-9919D4C7B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIsbh2_OTErq_vKoyOB4dehgKlGJ511E4',
    appId: '1:576136181155:android:e3729dc52638af3d8d1616',
    messagingSenderId: '576136181155',
    projectId: 'ecommerce-app-64233',
    storageBucket: 'ecommerce-app-64233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAekJj0PpXWVlhHuEUgmdQXGyo_cUgCkFE',
    appId: '1:576136181155:ios:ad3f389731efabfe8d1616',
    messagingSenderId: '576136181155',
    projectId: 'ecommerce-app-64233',
    storageBucket: 'ecommerce-app-64233.appspot.com',
    iosClientId: '576136181155-4hsrjau4lg1m2erkshrv2hefmndki15l.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAekJj0PpXWVlhHuEUgmdQXGyo_cUgCkFE',
    appId: '1:576136181155:ios:418d73dfb626af1f8d1616',
    messagingSenderId: '576136181155',
    projectId: 'ecommerce-app-64233',
    storageBucket: 'ecommerce-app-64233.appspot.com',
    iosClientId: '576136181155-r4bbs7tjjuggbvvhmjs8fv2ptsc2aq25.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
