// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzZ41QHNGIEZLcW8svOAvUv17Mk8U_098',
    appId: '1:112305148730:web:853a5efd22e965398db603',
    messagingSenderId: '112305148730',
    projectId: 'e-commerce-app-ef858',
    authDomain: 'e-commerce-app-ef858.firebaseapp.com',
    storageBucket: 'e-commerce-app-ef858.appspot.com',
    measurementId: 'G-XRKR22EG8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTlaAFmbTg5AdtX7-hmHGmuXAvEQlq6_k',
    appId: '1:112305148730:android:093f5b397e2797ba8db603',
    messagingSenderId: '112305148730',
    projectId: 'e-commerce-app-ef858',
    storageBucket: 'e-commerce-app-ef858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySR7Aov8oW8rcONaK61C1vzmvNmKjGeI',
    appId: '1:112305148730:ios:aa0d465bd6ee1a818db603',
    messagingSenderId: '112305148730',
    projectId: 'e-commerce-app-ef858',
    storageBucket: 'e-commerce-app-ef858.appspot.com',
    iosClientId: '112305148730-fvb43ck2djn6nvj8kq4md8tb13nncrs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCySR7Aov8oW8rcONaK61C1vzmvNmKjGeI',
    appId: '1:112305148730:ios:54d1f48144157d148db603',
    messagingSenderId: '112305148730',
    projectId: 'e-commerce-app-ef858',
    storageBucket: 'e-commerce-app-ef858.appspot.com',
    iosClientId: '112305148730-p3l3os8071p1m5v24q7bknuj7k2r3a19.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
